version: "2.15.1"

services:
 
  app:
    build: $BACKEND_PATH
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
 
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    depends_on:
      realestatedb: 
         condition: service_healthy

  realestatedb:
    image: mysql:$MYSQL_VERSION
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

    healthcheck:
      test: "mysqladmin ping -h localhost"
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  db: